
#==============================================================================
# Define specific objects required by this backend
#==============================================================================
 BKEND_OBJS +=                                    \
              $(OBJDIR)/core/sdl2/gfmAudio.o      \
              $(OBJDIR)/core/sdl2/gfmBackend.o    \
              $(OBJDIR)/core/sdl2/gfmEvent.o      \
              $(OBJDIR)/core/sdl2/gfmPath.o       \
              $(OBJDIR)/core/sdl2/gfmTimer.o      \
#==============================================================================

# Those files are going to be removed (eventually)
 BKEND_OBJS +=                                    \
              $(OBJDIR)/core/sdl2/gfmBackbuffer.o \
              $(OBJDIR)/core/sdl2/gfmTexture.o    \
              $(OBJDIR)/core/sdl2/gfmWindow.o     

