
#==============================================================================
# Define specific objects required by this backend
#==============================================================================
 BKEND_OBJS += \
               $(OBJDIR)/core/sdl2/gfmAudio.o \
               $(OBJDIR)/core/sdl2/gfmBackend.o \
               $(OBJDIR)/core/event/desktop/gfmEvent_desktop.o \
               $(OBJDIR)/core/sdl2/gfmPath.o \
               $(OBJDIR)/core/sdl2/gfmTimer.o    
#==============================================================================

