
#==============================================================================
# Define specific objects required by this backend
#==============================================================================
 BKEND_OBJS +=                                                    \
              $(OBJDIR)/core/video/gles2/gfmVideo_gles2.o         \
              $(OBJDIR)/core/video/gles2/gfmVideo_gles2_glFuncs.o 
#==============================================================================

