
#==============================================================================
# Define specific objects required by this backend
#==============================================================================
 BKEND_OBJS +=                                           \
               $(OBJDIR)/core/emscript-sdl2/gfmAudio.o   \
               $(OBJDIR)/core/emscript-sdl2/gfmBackend.o \
               $(OBJDIR)/core/sdl2/gfmEvent.o            \
               $(OBJDIR)/core/emscript-sdl2/gfmPath.o    \
               $(OBJDIR)/core/sdl2/gfmTimer.o            
#==============================================================================

