/**
 * Export all pointers to OpenGL functions
 *
 * @file src/core/video/opengl3/gfmVideo_opengl3_glFuncs.c
 */
#include <GFraMe/gfmAssert.h>
#include <GFraMe/gfmError.h>

#include <SDL2/SDL_video.h>
#include <SDL2/SDL_opengl.h>

/* Declare all OpenGL function pointer on a global context >_< */
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLDELETEBUFFERSPROC glDeleteBuffers;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
#if defined(_WIN32) || defined(_WIN64)
PFNGLACTIVETEXTUREPROC glActiveTexture;
#endif
PFNGLBINDSAMPLERPROC glBindSampler;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;

/**
 * Load all required OpenGL functions
 * 
 * @return  GFMRV_OK, GFMRV_INTERNAL_ERROR
 */
gfmRV gfmVideo_GL3_glLoadFunctions() {
    gfmRV rv;

#define LOAD_PROC(type, func) \
    func = (type) SDL_GL_GetProcAddress( #func ); \
    ASSERT(func, GFMRV_INTERNAL_ERROR); 

    LOAD_PROC(PFNGLUSEPROGRAMPROC, glUseProgram);
    LOAD_PROC(PFNGLUNIFORM2FPROC, glUniform2f);
    LOAD_PROC(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers);
    LOAD_PROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
    LOAD_PROC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
    LOAD_PROC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
#if defined(_WIN32) || defined(_WIN64)
    LOAD_PROC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
#endif
    LOAD_PROC(PFNGLBINDSAMPLERPROC, glBindSampler);
    LOAD_PROC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
    LOAD_PROC(PFNGLBINDBUFFERPROC, glBindBuffer);
    LOAD_PROC(PFNGLUNIFORM1IPROC, glUniform1i);
    LOAD_PROC(PFNGLUNIFORM1FPROC, glUniform1f);
    LOAD_PROC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
    LOAD_PROC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
    LOAD_PROC(PFNGLGENBUFFERSPROC, glGenBuffers);
    LOAD_PROC(PFNGLBUFFERDATAPROC, glBufferData);
    LOAD_PROC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
    LOAD_PROC(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);
    LOAD_PROC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
    LOAD_PROC(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D);
    LOAD_PROC(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus);
    LOAD_PROC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);
    LOAD_PROC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
    LOAD_PROC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
    LOAD_PROC(PFNGLATTACHSHADERPROC, glAttachShader);
    LOAD_PROC(PFNGLLINKPROGRAMPROC, glLinkProgram);
    LOAD_PROC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
    LOAD_PROC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
    LOAD_PROC(PFNGLDETACHSHADERPROC, glDetachShader);
    LOAD_PROC(PFNGLDELETESHADERPROC, glDeleteShader);
    LOAD_PROC(PFNGLCREATESHADERPROC, glCreateShader);
    LOAD_PROC(PFNGLSHADERSOURCEPROC, glShaderSource);
    LOAD_PROC(PFNGLCOMPILESHADERPROC, glCompileShader);
    LOAD_PROC(PFNGLGETSHADERIVPROC, glGetShaderiv);
    LOAD_PROC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
    LOAD_PROC(PFNGLVALIDATEPROGRAMPROC, glValidateProgram);
    LOAD_PROC(PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced);

#undef LOAD_PROC

    rv = GFMRV_OK;
__ret:
    return rv;
}

