
#==============================================================================
# Define specific objects required by this backend
#==============================================================================
 BKEND_OBJS +=                                                        \
              $(OBJDIR)/core/video/opengl3/gfmVideo_opengl3.o         \
              $(OBJDIR)/core/video/opengl3/gfmVideo_opengl3_glFuncs.o 
#==============================================================================

